version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
      cache_from:
        - python:3.9-slim-bullseye
    image: rag-chatbot:latest
    ports:
      - "8502:8502"
    env_file:
      - .env
    volumes:
      - ./:/app
      - ./source_pdfs:/app/source_pdfs
      - ./source_txts:/app/source_txts
      - ./source_chunks:/app/source_chunks
      - huggingface_cache:/huggingface
    environment:
      - STREAMLIT_SERVER_PORT=8502
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - PYTHONUNBUFFERED=1
      - HF_HOME=/huggingface
      - TRANSFORMERS_CACHE=/huggingface
      - XDG_CACHE_HOME=/huggingface
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G

volumes:
  huggingface_cache:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/huggingface_cache
